name = "FlexibleFunctors"
uuid = "0da941aa-91b6-4cc4-98e3-d6ba47d3ded9"
authors = ["Sam Buercklin <sam@metalenz.com>", "Pawel Latawiec <pawel@metalenz.com>"]
version = "0.1.4"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"

[compat]
ConstructionBase = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
